name: Learning to FLy
url: http://peteshaw.github.io
description: Just some random posts as I learn about all this cloud stuff.

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
markdown: kramdown
